sudo: required
services:
  - docker

before_install:
  - docker build -t maurice526/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maurice526/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "us-east-2"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-579415673533"
  bucket_path: "docker"
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
