sudo: required
services:
  - docker

before_install:
  - docker build -t maurice526/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maurice526/docker-react npm run test -- --coverage
